services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./log:/var/log/apache2
    ports:
      - 80:80
  mysql:
    image: mysql:5.6.51
    volumes:
      - ./mysql:/var/lib/mysql
  bower:
    container_name: bower
    build: docker/bower
    working_dir: /app
    volumes:
      - .:/app
